---
- name: Instalar Boost note
  hosts: all:!localhost
  become: yes

  tasks:
    - name: Instalar Boostnote
      ansible.builtin.apt:
        deb: "http://172.30.12.180/Ansible/boost-note-linux.deb"