- name: Install Ultimaker Cura System-Wide
  hosts: all:!localhost
  become: yes

  tasks:
    - name: Ensure Flathub repository is configured system-wide
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        method: system

    - name: Install Ultimaker Cura Flatpak
      community.general.flatpak:
        name: com.ultimaker.cura
        state: present
        method: system