- name: Instalar DataGrip mediante Snap
  hosts: all:!localhost
  become: yes
  
  tasks:
    - name: Instalar dependencias (snapd)
      apt:
        name:
          - snapd
        state: present

    - name: Instalar JetBrains DataGrip con confinamiento clásico
      community.general.snap:
        name: datagrip
        state: present
        classic: true
